In [1]:
import numpy as np 
import pandas as pd
import re

In [2]:
def clean_text(text):
    if isinstance(text, str): 
        return re.sub(r'\s+', ' ', text).strip()
    return text

In [3]:
def summary(df):
    print(f'data shape: {df.shape}')  
    summ = pd.DataFrame(df.dtypes, columns=['data type'])
    summ['#missing'] = df.isnull().sum().values 
    summ['%missing'] = df.isnull().sum().values / len(df)
    summ['#unique'] = df.nunique().values
    desc = pd.DataFrame(df.describe(include='all').transpose())
#     summ['min'] = desc['min'].values
#     summ['max'] = desc['max'].values
    return summ

In [4]:
file_path = '../metadata/hierarchy_topic_by_sheet.xlsx' 
xls = pd.ExcelFile(file_path)


dfs = {}

for sheet_name in xls.sheet_names:
    first_word = sheet_name.split()[0].lower() 
    df = pd.read_excel(xls, sheet_name=sheet_name)  
    dfs[first_word] = df  


for name, df in dfs.items():
    print(f"{name}")

economic
education
environment
financial
gender
health
infrastructure
poverty
private
public
social
trade

In [5]:
dfs['education']

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,SE.PRM.PRS5.ZS,"Persistence to grade 5, total (% of cohort)",Education: Efficiency,Education,Efficiency,NaN,NaN
1,SE.PRM.GINT.ZS,Gross intake ratio in first grade of primary e...,Education: Efficiency,Education,Efficiency,NaN,NaN
2,SE.PRM.NINT.ZS,Net intake rate in grade 1 (% of official scho...,Education: Efficiency,Education,Efficiency,NaN,NaN
3,SE.PRM.OENR.MA.ZS,"Over-age students, primary, male (% of male en...",Education: Efficiency,Education,Efficiency,NaN,NaN
4,SE.PRM.PRS5.MA.ZS,"Persistence to grade 5, male (% of cohort)",Education: Efficiency,Education,Efficiency,NaN,NaN
...,...,...,...,...,...,...,...
151,SE.ENR.PRIM.FM.ZS,"School enrollment, primary (gross), gender par...",Education: Participation,Education,Participation,NaN,NaN
152,SE.PRM.NENR,"School enrollment, primary (% net)",Education: Participation,Education,Participation,NaN,NaN
153,SE.PRE.ENRR.MA,"School enrollment, preprimary, male (% gross)",Education: Participation,Education,Participation,NaN,NaN
154,SE.PRM.PRIV.ZS,"School enrollment, primary, private (% of tota...",Education: Participation,Education,Participation,NaN,NaN
155,SE.ENR.TERT.FM.ZS,"School enrollment, tertiary (gross), gender pa...",Education: Participation,Education,Participation,NaN,NaN

In [6]:
example_education = dfs['education'].copy()

In [7]:
example_education['code3'] = example_education['Code'].str.split('.').str[:3].str.join('.')

In [8]:
grouped_counts = example_education['code3'].value_counts()
grouped_counts.head()

code3
SE.TER.CUAT    12
SE.SEC.CUAT     9
SE.LPV.PRIM     9
SE.SEC.TCAQ     9
SE.SEC.ENRL     9
Name: count, dtype: int64

In [9]:

with pd.option_context('display.max_colwidth', 200):

    display(example_education[example_education['code3'] == 'SE.TER.CUAT'])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3,code3
68,SE.TER.CUAT.BA.FE.ZS,"Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
69,SE.TER.CUAT.DO.FE.ZS,"Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
70,SE.TER.CUAT.BA.MA.ZS,"Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
71,SE.TER.CUAT.DO.MA.ZS,"Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
73,SE.TER.CUAT.ST.FE.ZS,"Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
76,SE.TER.CUAT.ST.MA.ZS,"Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
77,SE.TER.CUAT.MS.ZS,"Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
78,SE.TER.CUAT.BA.ZS,"Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
80,SE.TER.CUAT.DO.ZS,"Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
81,SE.TER.CUAT.MS.MA.ZS,"Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
82,SE.TER.CUAT.MS.FE.ZS,"Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT
83,SE.TER.CUAT.ST.ZS,"Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)",Education: Outcomes,Education,Outcomes,NaN,NaN,SE.TER.CUAT

In this eample of education outcomes, we observe that indicator codes beginning with **SE.TER.CUAT** can be further subdivided to populate relevant subtopics.  

To achieve this, we will:  
1. **Read the WDI Indicators file** to examine the full list of codes and their corresponding descriptions.  
2. **Identify patterns** within the codes that allow for classification into subtopics.  
3. **Extract meaningful subtopic information** from the code structure and descriptions.  

By implementing this approach, we aim to enhance the granularity of our dataset and improve analytical insights into education outcomes.

In [10]:
wdi_codes = pd.read_excel('../metadata/WDI_Indicators.xlsx', sheet_name="Coding")

In [11]:
wdi_codes

,Topic,Topic description,General subject,General subject description,Specific subject,Specific subject description,Extensions,Extensions description
0,AG,Agriculture,ACS,Access,0003,Age 0-3,05,2005 (PPP)
1,BG,Balance of payments: gross,ADJ,Adjusted savings,0004,Age 0-4,10,Decile
2,BM,"Balance of payments: imports, payments (credit)",ADM,Admission,0014,Age 0-14,14,Age 0-14
3,BN,Balance of payments: net,ADO,Adolescent,0324,Age 0-24,20,Quintile
4,BX,"Balance of payments: exports, receipts (debit)",ADT,Adult,0306,Age 3-6,90,% changes since 1990
...,...,...,...,...,...,...,...,...
1057,NaN,NaN,NaN,NaN,XOKA,Excluding official capital transfers,NaN,NaN
1058,NaN,NaN,NaN,NaN,XPND,Expenditure,NaN,NaN
1059,NaN,NaN,NaN,NaN,XPRT,Exports,NaN,NaN
1060,NaN,NaN,NaN,NaN,XTHR,Other manufactures (trade),NaN,NaN
1061,NaN,NaN,NaN,NaN,YPKG,"Income, profits and capital gains",NaN,NaN

### Understanding the Code Structure using `wdi_codes`

Based on our analysis, we have identified a general pattern in the structure of the codes formatted as **XX.XX.XX...**. While this does not apply to all cases, the common breakdown is as follows:

1. **Topic Column**: Corresponds to the `Topic` and `SubTopic1` of the dataset as the values for that column are **name : name**.
2. **General subject Column**: Represents the `SubTopic2`.
3. **Specific subject Column**: Defines the `SubTopic3`.
4. **Extension (the rest)**: Any additional components following the third part can be considered as **Extensions**, which provide further granularity or variations within the specific subject. Note we dont have a column for taht yet and we will find a way to add informations of extension if they are important to our work

By leveraging this structure, we can systematically extract hierarchical information from the codes and use it for improved classification and mapping in our analysis.

We will delete the topic and topic description as we already has the topic metadata filled

In [12]:
wdi_codes.drop(columns=['Topic', 'Topic description'], inplace=True)
wdi_codes.head()

,General subject,General subject description,Specific subject,Specific subject description,Extensions,Extensions description
0,ACS,Access,0003,Age 0-3,05,2005 (PPP)
1,ADJ,Adjusted savings,0004,Age 0-4,10,Decile
2,ADM,Admission,0014,Age 0-14,14,Age 0-14
3,ADO,Adolescent,0324,Age 0-24,20,Quintile
4,ADT,Adult,0306,Age 3-6,90,% changes since 1990

In [13]:
for col in ['General subject', 'Specific subject', 'Extensions']:
    redundant = wdi_codes[col].dropna()[wdi_codes[col].dropna().duplicated()]
    if not redundant.empty:
        print(f"Redundant values in column '{col}':")
        print(redundant)
    else:
        print(f"No redundant values in column '{col}'.")

No redundant values in column 'General subject'.
No redundant values in column 'Specific subject'.
No redundant values in column 'Extensions'.

In [14]:
import pandas as pd

wdi_codes['has_match'] = wdi_codes.apply(
    lambda row: (
        (pd.notna(row['General subject']) and row['General subject'] in [row['Specific subject'], row['Extensions']]) or
        (pd.notna(row['Specific subject']) and row['Specific subject'] in [row['General subject'], row['Extensions']]) or
        (pd.notna(row['Extensions']) and row['Extensions'] in [row['General subject'], row['Specific subject']])
    ), axis=1
)

matching_rows = wdi_codes[wdi_codes['has_match']]
print("Rows with matching values between columns:")
print(matching_rows[['General subject', 'Specific subject', 'Extensions']])


wdi_codes.drop(columns=['has_match'], inplace=True)

Rows with matching values between columns:
Empty DataFrame
Columns: [General subject, Specific subject, Extensions]
Index: []

In [15]:
# df_melted = pd.melt(wdi_codes, 
#                     value_vars=['General subject', 'Specific subject', 'Extensions'], 
#                     var_name='Key_Type', value_name='Key')

# df_melted['Value'] = pd.melt(wdi_codes, 
#                              value_vars=['General subject description', 'Specific subject description', 'Extensions description'], 
#                              var_name='Value_Type', value_name='Value')['Value']

# df_melted.dropna(subset=['Key', 'Value'], how='any', inplace=True)

In [16]:
# df_melted

## Testing in the example of education `example_education`

In [17]:
print(example_education['SubTopic2'].notna().any())
print(example_education['SubTopic3'].notna().any())

False
False

# This is the main function we will be using to assign the subtopics

In [18]:
def extract_and_match(row, df2):

    parts = row['Code'].split('.')
    if len(parts) < 3:
        first_desc, second_desc = None, None
    else:
        first_desc = df2.loc[df2['General subject'] == parts[1], 'General subject description'].values
        second_desc = df2.loc[df2['Specific subject'] == parts[2], 'Specific subject description'].values

        first_desc = first_desc[0] if first_desc.size > 0 else None
        second_desc = second_desc[0] if second_desc.size > 0 else None


    if pd.notna(row['SubTopic2']):


        if first_desc != None and row['SubTopic2'] != first_desc: 

            row['SubTopic2'] = [row['SubTopic2'], first_desc]            
    else:

        row['SubTopic2'] = first_desc

    if pd.notna(row['SubTopic3']):

        if row['SubTopic3'] != second_desc:
            row['SubTopic3'] = [row['SubTopic3'], second_desc]
    else:

        row['SubTopic3'] = second_desc

    return row

In [19]:
example_education = example_education.apply(extract_and_match, axis=1, df2=wdi_codes)

In [20]:
example_education

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3,code3
0,SE.PRM.PRS5.ZS,"Persistence to grade 5, total (% of cohort)",Education: Efficiency,Education,Efficiency,Primary education,Persistence to grade 5,SE.PRM.PRS5
1,SE.PRM.GINT.ZS,Gross intake ratio in first grade of primary e...,Education: Efficiency,Education,Efficiency,Primary education,Gross intake,SE.PRM.GINT
2,SE.PRM.NINT.ZS,Net intake rate in grade 1 (% of official scho...,Education: Efficiency,Education,Efficiency,Primary education,Net intake,SE.PRM.NINT
3,SE.PRM.OENR.MA.ZS,"Over-age students, primary, male (% of male en...",Education: Efficiency,Education,Efficiency,Primary education,Over-age enrollment,SE.PRM.OENR
4,SE.PRM.PRS5.MA.ZS,"Persistence to grade 5, male (% of cohort)",Education: Efficiency,Education,Efficiency,Primary education,Persistence to grade 5,SE.PRM.PRS5
...,...,...,...,...,...,...,...,...
151,SE.ENR.PRIM.FM.ZS,"School enrollment, primary (gross), gender par...",Education: Participation,Education,Participation,Enrollment,Primary education,SE.ENR.PRIM
152,SE.PRM.NENR,"School enrollment, primary (% net)",Education: Participation,Education,Participation,Primary education,Net enrollment,SE.PRM.NENR
153,SE.PRE.ENRR.MA,"School enrollment, preprimary, male (% gross)",Education: Participation,Education,Participation,Preprimary education,Enrolment rate,SE.PRE.ENRR
154,SE.PRM.PRIV.ZS,"School enrollment, primary, private (% of tota...",Education: Participation,Education,Participation,Primary education,Private,SE.PRM.PRIV
155,SE.ENR.TERT.FM.ZS,"School enrollment, tertiary (gross), gender pa...",Education: Participation,Education,Participation,Enrollment,Tertiary education,SE.ENR.TERT

In [21]:
summary(example_education).style.background_gradient(cmap='Blues')

data shape: (156, 8)

In [22]:
with pd.option_context('display.max_colwidth', 200):

    display(example_education[example_education['SubTopic2'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3,code3
75,SE.LPV.PRIM.SD,Primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
89,SE.LPV.PRIM.LD,Pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
94,SE.LPV.PRIM.MA,Learning poverty: Share of Male Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
95,SE.LPV.PRIM.FE,Learning poverty: Share of Female Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
101,SE.LPV.PRIM,Learning poverty: Share of Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
104,SE.LPV.PRIM.LD.FE,Female pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
105,SE.LPV.PRIM.SD.FE,Female primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
106,SE.LPV.PRIM.SD.MA,Male primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM
109,SE.LPV.PRIM.LD.MA,Male pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education,SE.LPV.PRIM

In [23]:
example_education['SubTopic2'] = example_education['SubTopic2'].fillna('Low Poverty Vulnerability')
summary(example_education).style.background_gradient(cmap='Blues')

data shape: (156, 8)

## In this example
As we can see, we were able to extend the granularity and hierarchy of the education metadata.

There are missing values for subtopic1, and after further research, we can impute these with the value **LPV = 'Low Poverty Vulnerability'**.

For now, this will be done manually for each sheet.

## We apply our function to the entire df

In [24]:
for key, df in dfs.items():

    df = df.apply(extract_and_match, axis=1, df2=wdi_codes)  
    dfs[key] = df

In [25]:
for key, df in dfs.items():

    missing_subtopic2 = df['SubTopic2'].isnull().sum()
    missing_subtopic3 = df['SubTopic3'].isnull().sum()
    

    print(f"\n{'*' * 10} {key} {'*' * 10}")
    print(f"Missing subtopic2: {missing_subtopic2}")
    print(f"Missing subtopic3: {missing_subtopic3}")
    print("-" * 40)

********** economic **********
Missing subtopic2: 0
Missing subtopic3: 15
----------------------------------------

********** education **********
Missing subtopic2: 9
Missing subtopic3: 0
----------------------------------------

********** environment **********
Missing subtopic2: 43
Missing subtopic3: 44
----------------------------------------

********** financial **********
Missing subtopic2: 0
Missing subtopic3: 0
----------------------------------------

********** gender **********
Missing subtopic2: 1
Missing subtopic3: 2
----------------------------------------

********** health **********
Missing subtopic2: 12
Missing subtopic3: 45
----------------------------------------

********** infrastructure **********
Missing subtopic2: 0
Missing subtopic3: 0
----------------------------------------

********** poverty **********
Missing subtopic2: 0
Missing subtopic3: 9
----------------------------------------

********** private **********
Missing subtopic2: 6
Missing subtopic3: 1
----------------------------------------

********** public **********
Missing subtopic2: 51
Missing subtopic3: 42
----------------------------------------

********** social **********
Missing subtopic2: 27
Missing subtopic3: 27
----------------------------------------

********** trade **********
Missing subtopic2: 0
Missing subtopic3: 0
----------------------------------------

### For now i think the best way is to go throught each individually and handle missing and the different values in "list" subtopics (chatgpt + wdi documentation)

# Economic

In [26]:
economic = dfs["economic"]

**Notice we dont create a copy as we want the changes to reflect to dfs["economic"].**

In [27]:
with pd.option_context('display.max_colwidth', 200):

    display(economic[economic['SubTopic3'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
269,DT.NFL.WITC.CD,"Net official flows from UN agencies, WTO-ITC (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
286,DC.DAC.LTUL.CD,"Net bilateral aid flows from DAC donors, Lithuania (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Development Assistance Committee (OECD),None
304,DT.NFL.CERF.CD,"Net official flows from UN agencies, CERF (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
308,DT.NFL.UNCTAD.CD,"Net official flows from UN agencies, UNCTAD (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
311,DT.NFL.UNEP.CD,"Net official flows from UN agencies, UNEP (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
315,DT.NFL.UNID.CD,"Net official flows from UN agencies, UNIDIR (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
316,DT.NFL.UNIDO.CD,"Net official flows from UN agencies, UNIDO (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
319,DT.NFL.UNWN.CD,"Net official flows from UN agencies, UNWOMEN (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
320,DT.NFL.UNWT.CD,"Net official flows from UN agencies, UNWTO (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
323,DT.NFL.UNCV.CD,"Net official flows from UN agencies, UNCOVID (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
324,DT.NFL.UNCD.CD,"Net official flows from UN agencies, UNCDF (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
326,DT.NFL.SPRP.CD,"Net official flows from UN agencies, SPRP (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None
329,DC.DAC.HUNL.CD,"Net bilateral aid flows from DAC donors, Hungary (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Development Assistance Committee (OECD),None
335,DC.DAC.ESTL.CD,"Net bilateral aid flows from DAC donors, Estonia (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Development Assistance Committee (OECD),None
337,DT.NFL.SDGF.CD,"Net official flows from UN agencies, SDGFUND (current US$)",Economic Policy & Debt: Official development assistance,Economic Policy & Debt,Official development assistance,Net flows,None

In [28]:
economic_mapping = {
    "WITC": "World Integrated Trade Solution",
    "LTUL": "Long-Term Unemployment Level",
    "CERF": "Central Emergency Response Fund",
    "UNCTAD": "United Nations Conference on Trade and Development",
    "UNEP": "United Nations Environment Programme",
    "UNID": "United Nations Industrial Development Organization",
    "UNIDO": "United Nations Industrial Development Organization",
    "UNWN": "United Nations World Network (Unconfirmed)",
    "UNCV": "United Nations Convention",
    "SPRP": "Social Protection and Resilience Programs",
    "HUNL": "Hunger Levels (Unconfirmed)",
    "ESTL": "Estimated Labor Statistics",
    "SDGF": "Sustainable Development Goals Fund",
    "UNWT": "United Nations World Tourism Organization",
    "UNCD": "United Nations Conference on Disarmament"


}

economic.loc[economic["SubTopic3"].isna(), "SubTopic3"] = (
    economic["Code"].str.split(".").str[2].map(economic_mapping)
)

In [29]:
with pd.option_context('display.max_colwidth', 200):

    display(economic[economic['SubTopic3'].isna()])

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

In [50]:
def get_code_prefix(code):
    return ".".join(code.split(".")[:2])

filtered = economic[
    economic['SubTopic2'].apply(lambda x: isinstance(x, list)) | 
    economic['SubTopic3'].apply(lambda x: isinstance(x, list))
]

filtered = filtered.copy()
filtered.loc[:, "CodeGroup"] = filtered["Code"].apply(get_code_prefix)


grouped = filtered.groupby("CodeGroup")

In [67]:
group_keys = list(grouped.groups.keys())

index = 12  

selected_group_key = group_keys[index]
selected_group_df = grouped.get_group(selected_group_key)


with pd.option_context('display.max_colwidth', 200):

    display(selected_group_df)

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3,CodeGroup
4,BX.GSR.CMCP.ZS,"Communications, computer, etc. (% of service exports, BoP)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Communications, computer, etc.]",BX.GSR
5,BX.GSR.FCTY.CD,"Primary income receipts (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Factor income]",BX.GSR
13,BX.GSR.GNFS.CD,"Exports of goods and services (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Goods and (nonfactor) services]",BX.GSR
15,BX.GSR.TRAN.ZS,"Transport services (% of service exports, BoP)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Transport]",BX.GSR
17,BX.GSR.TOTL.CD,"Exports of goods, services and primary income (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Total]",BX.GSR
21,BX.GSR.INSF.ZS,"Insurance and financial services (% of service exports, BoP)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Insurance and financial services]",BX.GSR
24,BX.GSR.NFSV.CD,"Service exports (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, (Nonfactor) services]",BX.GSR
29,BX.GSR.ROYL.CD,"Charges for the use of intellectual property, receipts (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Royalty and license fees]",BX.GSR
38,BX.GSR.TRVL.ZS,"Travel services (% of service exports, BoP)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Travel]",BX.GSR
49,BX.GSR.MRCH.CD,"Goods exports (BoP, current US$)","Economic Policy & Debt: Balance of payments: Current account: Goods, services & income",Economic Policy & Debt,Balance of payments,"[Current account, Goods and services]","[Goods, services & income, Goods (merchandise)]",BX.GSR

### For the various examples we analyzed, we concluded that selecting the values added from the WDI (World Development Indicators) dataset provides a more accurate representation. These values offer a finer level of granularity, enhancing our ability to analyze and interpret the data effectively.

In [85]:
def select_second_item(value):
    if isinstance(value, list) and len(value) > 1:
        return value[1]  
    return value

In [88]:
economic["SubTopic2"] = economic["SubTopic2"].apply(select_second_item)
economic["SubTopic3"] = economic["SubTopic3"].apply(select_second_item)

# Education

In [92]:
education = dfs['education']

In [93]:
with pd.option_context('display.max_colwidth', 200):

    display(education[education['SubTopic2'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
75,SE.LPV.PRIM.SD,Primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education
89,SE.LPV.PRIM.LD,Pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education
94,SE.LPV.PRIM.MA,Learning poverty: Share of Male Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education
95,SE.LPV.PRIM.FE,Learning poverty: Share of Female Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education
101,SE.LPV.PRIM,Learning poverty: Share of Children at the End-of-Primary age below minimum reading proficiency adjusted by Out-of-School Children (%),Education: Outcomes,Education,Outcomes,None,Primary education
104,SE.LPV.PRIM.LD.FE,Female pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education
105,SE.LPV.PRIM.SD.FE,Female primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education
106,SE.LPV.PRIM.SD.MA,Male primary school age children out-of-school (%),Education: Outcomes,Education,Outcomes,None,Primary education
109,SE.LPV.PRIM.LD.MA,Male pupils below minimum reading proficiency at end of primary (%). Low GAML threshold,Education: Outcomes,Education,Outcomes,None,Primary education

In [94]:
education['SubTopic2'] = education['SubTopic2'].fillna('Low Poverty Vulnerability')

In [96]:
with pd.option_context('display.max_colwidth', 200):

    display(education[education['SubTopic3'].isna()])

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

In [99]:
has_list = education.apply(lambda row: isinstance(row['SubTopic2'], list) or isinstance(row['SubTopic3'], list), axis=1)


education_with_lists = education[has_list]
print(education_with_lists)

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

# Environment

In [102]:
environment = dfs["environment"]

In [105]:
with pd.option_context('display.max_colwidth', 200):

    display(environment[(environment['SubTopic2'].isna())|(environment['SubTopic3'].isna())])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
65,ER.H2O.FWST.ZS,Level of water stress: freshwater withdrawal as a proportion of available freshwater resources,Environment: Freshwater,Environment,Freshwater,Water,None
71,EN.GHG.ALL.LU.MT.CE.AR5,Total greenhouse gas emissions including LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
72,EN.GHG.ALL.PC.CE.AR5,Total greenhouse gas emissions per capita excluding LULUCF (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
73,EN.GHG.CO2.MT.CE.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
74,EN.GHG.CO2.LU.DF.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
75,EN.GHG.CO2.LU.OS.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
76,EN.GHG.FGAS.IP.MT.CE.AR5,Fluorinated greenhouse gases (F-gases) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
77,EN.GHG.ALL.MT.CE.AR5,Total greenhouse gas emissions excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
78,EN.GHG.CO2.ZG.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
79,EN.GHG.CO2.LU.OL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
80,EN.GHG.CO2.RT.GDP.PP.KD,Carbon intensity of GDP (kg CO2e per 2021 PPP $),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
81,EN.GHG.CO2.RT.GDP.KD,Carbon intensity of GDP (kg CO2e per constant 2021 US$ of GDP),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
82,EN.GHG.CO2.LU.FL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
83,EN.GHG.CO2.LU.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
84,EN.GHG.TOT.ZG.AR5,Total greenhouse gas emissions excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
85,EN.GHG.CO2.WA.MT.CE.AR5,Carbon dioxide (CO2) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
86,EN.GHG.N2O.IC.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
87,EN.GHG.CH4.ZG.AR5,Methane (CH4) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
88,EN.GHG.N2O.ZG.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
89,EN.GHG.N2O.FE.MT.CE.AR5,Nitrous oxide (N2O) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
90,EN.GHG.N2O.BU.MT.CE.AR5,Nitrous oxide (N2O) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
91,EN.GHG.CH4.BU.MT.CE.AR5,Methane (CH4) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
92,EN.GHG.CH4.FE.MT.CE.AR5,Methane (CH4) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
93,EN.GHG.N2O.PI.MT.CE.AR5,Nitrous oxide (N2O) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
94,EN.GHG.N2O.TR.MT.CE.AR5,Nitrous oxide (N2O) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
95,EN.GHG.N2O.MT.CE.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
96,EN.GHG.N2O.WA.MT.CE.AR5,Nitrous oxide (N2O) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
97,EN.GHG.CH4.MT.CE.AR5,Methane (CH4) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
98,EN.GHG.N2O.IP.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
99,EN.GHG.CH4.IC.MT.CE.AR5,Methane (CH4) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
100,EN.GHG.CH4.IP.MT.CE.AR5,Methane (CH4) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
101,EN.GHG.CH4.WA.MT.CE.AR5,Methane (CH4) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
102,EN.GHG.CH4.PI.MT.CE.AR5,Methane (CH4) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
103,EN.GHG.CH4.AG.MT.CE.AR5,Methane (CH4) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
104,EN.GHG.CO2.TR.MT.CE.AR5,Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
105,EN.GHG.CO2.PI.MT.CE.AR5,Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
106,EN.GHG.CO2.IP.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
107,EN.GHG.CH4.TR.MT.CE.AR5,Methane (CH4) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
108,EN.GHG.CO2.IC.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
109,EN.GHG.CO2.FE.MT.CE.AR5,Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
110,EN.GHG.CO2.BU.MT.CE.AR5,Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
111,EN.GHG.CO2.AG.MT.CE.AR5,Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
112,EN.GHG.N2O.AG.MT.CE.AR5,Nitrous oxide (N2O) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None
113,EN.GHG.CO2.PC.CE.AR5,Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,None,None

In [115]:
# environment_mapping_subtopic3 = {
#     "FWST": "freshwater withdrawal"
# }

In [123]:
environment.loc[environment["Code"] == "ER.H2O.FWST.ZS", "SubTopic3"] = "Water stress: freshwater withdrawal"

In [109]:
environment_mapping = {
    "ALL": "All Greenhouse Gases",
    "FGAS": "Fluorinated Gases emissions",
    "CH4": "Methane emissions",
    "N2O": "Nitrous oxide emissions",
    "CO2": "Carbon dioxide emissions",
    "TOT": "Total"
}

environment.loc[environment["SubTopic2"].isna(), "SubTopic2"] = (
    environment["Code"].str.split(".").str[2].map(environment_mapping)
)

In [118]:
with pd.option_context('display.max_colwidth', 200):

    display(environment[environment['SubTopic2'].isna()])

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

In [124]:
with pd.option_context('display.max_colwidth', 200):

    display(environment[environment['SubTopic3'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
72,EN.GHG.ALL.PC.CE.AR5,Total greenhouse gas emissions per capita excluding LULUCF (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,NaN
73,EN.GHG.CO2.MT.CE.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN
77,EN.GHG.ALL.MT.CE.AR5,Total greenhouse gas emissions excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,NaN
78,EN.GHG.CO2.ZG.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN
84,EN.GHG.TOT.ZG.AR5,Total greenhouse gas emissions excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Total,NaN
87,EN.GHG.CH4.ZG.AR5,Methane (CH4) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,NaN
88,EN.GHG.N2O.ZG.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,NaN
95,EN.GHG.N2O.MT.CE.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,NaN
97,EN.GHG.CH4.MT.CE.AR5,Methane (CH4) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,NaN
113,EN.GHG.CO2.PC.CE.AR5,Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN

In [114]:
environment_mapping_subtopic3 = {
    "LU": "Including Land Use and Land-Use Change (LULUC)",
    "RT": "Carbon intensity of GDP",
    "OS": "Other Sources",
    "OL": "Other Land Use",
    "WA": "Waste",
    "IC": "Industrial Combustion",
    "IP": "Industrial Processes",
    "BU": "Buildings",
    "AG": "Agriculture",
    "PI": "Power Industry",
    "TR": "Transport",
    "FE": "Fugitive Emissions",

}

environment.loc[environment["SubTopic3"].isna(), "SubTopic3"] = (
    environment["Code"].str.split(".").str[3].map(environment_mapping_subtopic3)
)

In [119]:
with pd.option_context('display.max_colwidth', 200):
    display(environment[environment['Code'].str.startswith('EN.GHG')])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
71,EN.GHG.ALL.LU.MT.CE.AR5,Total greenhouse gas emissions including LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,Including Land Use and Land-Use Change (LULUC)
72,EN.GHG.ALL.PC.CE.AR5,Total greenhouse gas emissions per capita excluding LULUCF (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,NaN
73,EN.GHG.CO2.MT.CE.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN
74,EN.GHG.CO2.LU.DF.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
75,EN.GHG.CO2.LU.OS.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
76,EN.GHG.FGAS.IP.MT.CE.AR5,Fluorinated greenhouse gases (F-gases) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Fluorinated Gases,Industrial Processes
77,EN.GHG.ALL.MT.CE.AR5,Total greenhouse gas emissions excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,NaN
78,EN.GHG.CO2.ZG.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN
79,EN.GHG.CO2.LU.OL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
80,EN.GHG.CO2.RT.GDP.PP.KD,Carbon intensity of GDP (kg CO2e per 2021 PPP $),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Carbon intensity of GDP
81,EN.GHG.CO2.RT.GDP.KD,Carbon intensity of GDP (kg CO2e per constant 2021 US$ of GDP),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Carbon intensity of GDP
82,EN.GHG.CO2.LU.FL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
83,EN.GHG.CO2.LU.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
84,EN.GHG.TOT.ZG.AR5,Total greenhouse gas emissions excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Total,NaN
85,EN.GHG.CO2.WA.MT.CE.AR5,Carbon dioxide (CO2) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Waste
86,EN.GHG.N2O.IC.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Industrial Combustion
87,EN.GHG.CH4.ZG.AR5,Methane (CH4) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,NaN
88,EN.GHG.N2O.ZG.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,NaN
89,EN.GHG.N2O.FE.MT.CE.AR5,Nitrous oxide (N2O) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Fugitive Emissions
90,EN.GHG.N2O.BU.MT.CE.AR5,Nitrous oxide (N2O) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Buildings
91,EN.GHG.CH4.BU.MT.CE.AR5,Methane (CH4) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Buildings
92,EN.GHG.CH4.FE.MT.CE.AR5,Methane (CH4) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Fugitive Emissions
93,EN.GHG.N2O.PI.MT.CE.AR5,Nitrous oxide (N2O) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Power Industry
94,EN.GHG.N2O.TR.MT.CE.AR5,Nitrous oxide (N2O) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Transport
95,EN.GHG.N2O.MT.CE.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,NaN
96,EN.GHG.N2O.WA.MT.CE.AR5,Nitrous oxide (N2O) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Waste
97,EN.GHG.CH4.MT.CE.AR5,Methane (CH4) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,NaN
98,EN.GHG.N2O.IP.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Industrial Processes
99,EN.GHG.CH4.IC.MT.CE.AR5,Methane (CH4) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Industrial Combustion
100,EN.GHG.CH4.IP.MT.CE.AR5,Methane (CH4) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Industrial Processes
101,EN.GHG.CH4.WA.MT.CE.AR5,Methane (CH4) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Waste
102,EN.GHG.CH4.PI.MT.CE.AR5,Methane (CH4) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Power Industry
103,EN.GHG.CH4.AG.MT.CE.AR5,Methane (CH4) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Agriculture
104,EN.GHG.CO2.TR.MT.CE.AR5,Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Transport
105,EN.GHG.CO2.PI.MT.CE.AR5,Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Power Industry
106,EN.GHG.CO2.IP.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Industrial Processes
107,EN.GHG.CH4.TR.MT.CE.AR5,Methane (CH4) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Transport
108,EN.GHG.CO2.IC.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Industrial Combustion
109,EN.GHG.CO2.FE.MT.CE.AR5,Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Fugitive Emissions
110,EN.GHG.CO2.BU.MT.CE.AR5,Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Buildings
111,EN.GHG.CO2.AG.MT.CE.AR5,Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Agriculture
112,EN.GHG.N2O.AG.MT.CE.AR5,Nitrous oxide (N2O) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Agriculture
113,EN.GHG.CO2.PC.CE.AR5,Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,NaN

In [132]:
environment.loc[environment["SubTopic3"].isna(), "SubTopic3"] = "Excluding  Land Use and Land-Use Change (LULUC)"

In [133]:
with pd.option_context('display.max_colwidth', 200):
    display(environment[environment['Code'].str.startswith('EN.GHG')])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
71,EN.GHG.ALL.LU.MT.CE.AR5,Total greenhouse gas emissions including LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,Including Land Use and Land-Use Change (LULUC)
72,EN.GHG.ALL.PC.CE.AR5,Total greenhouse gas emissions per capita excluding LULUCF (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,Excluding Land Use and Land-Use Change (LULUC)
73,EN.GHG.CO2.MT.CE.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Excluding Land Use and Land-Use Change (LULUC)
74,EN.GHG.CO2.LU.DF.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
75,EN.GHG.CO2.LU.OS.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
76,EN.GHG.FGAS.IP.MT.CE.AR5,Fluorinated greenhouse gases (F-gases) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Fluorinated Gases,Industrial Processes
77,EN.GHG.ALL.MT.CE.AR5,Total greenhouse gas emissions excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,All Greenhouse Gases,Excluding Land Use and Land-Use Change (LULUC)
78,EN.GHG.CO2.ZG.AR5,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Excluding Land Use and Land-Use Change (LULUC)
79,EN.GHG.CO2.LU.OL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
80,EN.GHG.CO2.RT.GDP.PP.KD,Carbon intensity of GDP (kg CO2e per 2021 PPP $),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Carbon intensity of GDP
81,EN.GHG.CO2.RT.GDP.KD,Carbon intensity of GDP (kg CO2e per constant 2021 US$ of GDP),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Carbon intensity of GDP
82,EN.GHG.CO2.LU.FL.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
83,EN.GHG.CO2.LU.MT.CE.AR5,Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Including Land Use and Land-Use Change (LULUC)
84,EN.GHG.TOT.ZG.AR5,Total greenhouse gas emissions excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Total,Excluding Land Use and Land-Use Change (LULUC)
85,EN.GHG.CO2.WA.MT.CE.AR5,Carbon dioxide (CO2) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Waste
86,EN.GHG.N2O.IC.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Industrial Combustion
87,EN.GHG.CH4.ZG.AR5,Methane (CH4) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Excluding Land Use and Land-Use Change (LULUC)
88,EN.GHG.N2O.ZG.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (% change from 1990),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Excluding Land Use and Land-Use Change (LULUC)
89,EN.GHG.N2O.FE.MT.CE.AR5,Nitrous oxide (N2O) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Fugitive Emissions
90,EN.GHG.N2O.BU.MT.CE.AR5,Nitrous oxide (N2O) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Buildings
91,EN.GHG.CH4.BU.MT.CE.AR5,Methane (CH4) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Buildings
92,EN.GHG.CH4.FE.MT.CE.AR5,Methane (CH4) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Fugitive Emissions
93,EN.GHG.N2O.PI.MT.CE.AR5,Nitrous oxide (N2O) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Power Industry
94,EN.GHG.N2O.TR.MT.CE.AR5,Nitrous oxide (N2O) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Transport
95,EN.GHG.N2O.MT.CE.AR5,Nitrous oxide (N2O) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Excluding Land Use and Land-Use Change (LULUC)
96,EN.GHG.N2O.WA.MT.CE.AR5,Nitrous oxide (N2O) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Waste
97,EN.GHG.CH4.MT.CE.AR5,Methane (CH4) emissions (total) excluding LULUCF (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Excluding Land Use and Land-Use Change (LULUC)
98,EN.GHG.N2O.IP.MT.CE.AR5,Nitrous oxide (N2O) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Industrial Processes
99,EN.GHG.CH4.IC.MT.CE.AR5,Methane (CH4) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Industrial Combustion
100,EN.GHG.CH4.IP.MT.CE.AR5,Methane (CH4) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Industrial Processes
101,EN.GHG.CH4.WA.MT.CE.AR5,Methane (CH4) emissions from Waste (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Waste
102,EN.GHG.CH4.PI.MT.CE.AR5,Methane (CH4) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Power Industry
103,EN.GHG.CH4.AG.MT.CE.AR5,Methane (CH4) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Agriculture
104,EN.GHG.CO2.TR.MT.CE.AR5,Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Transport
105,EN.GHG.CO2.PI.MT.CE.AR5,Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Power Industry
106,EN.GHG.CO2.IP.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Industrial Processes
107,EN.GHG.CH4.TR.MT.CE.AR5,Methane (CH4) emissions from Transport (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Methane emissions,Transport
108,EN.GHG.CO2.IC.MT.CE.AR5,Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Industrial Combustion
109,EN.GHG.CO2.FE.MT.CE.AR5,Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Fugitive Emissions
110,EN.GHG.CO2.BU.MT.CE.AR5,Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Buildings
111,EN.GHG.CO2.AG.MT.CE.AR5,Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Agriculture
112,EN.GHG.N2O.AG.MT.CE.AR5,Nitrous oxide (N2O) emissions from Agriculture (Mt CO2e),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Nitrous oxide emissions,Agriculture
113,EN.GHG.CO2.PC.CE.AR5,Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita),Environment: Greenhouse Gas Emissions,Environment,Greenhouse Gas Emissions,Carbon dioxide emissions,Excluding Land Use and Land-Use Change (LULUC)

In [131]:
has_list = environment.apply(lambda row: isinstance(row['SubTopic2'], list) or isinstance(row['SubTopic3'], list), axis=1)


environment_with_lists = environment[has_list]
print(environment_with_lists)

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

# Financial

In [135]:
financial  = dfs["financial"]

In [137]:
with pd.option_context('display.max_colwidth', 200):

    display(financial[financial['SubTopic2'].isna() | financial['SubTopic3'].isna()])

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

In [139]:
financial

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,FX.OWN.TOTL.SO.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
1,FB.ATM.TOTL.P5,"Automated teller machines (ATMs) (per 100,000 ...",Financial Sector: Access,Financial Sector,Access,Atmosphere (or automated teller machine),Total
2,FX.OWN.TOTL.YG.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
3,FX.OWN.TOTL.60.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
4,FX.OWN.TOTL.MA.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
5,FX.OWN.TOTL.OL.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
6,FX.OWN.TOTL.40.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
7,SI.RMT.COST.IB.ZS,Average transaction cost of sending remittance...,Financial Sector: Access,Financial Sector,Access,Remittances,Cost
8,SI.RMT.COST.OB.ZS,Average transaction cost of sending remittance...,Financial Sector: Access,Financial Sector,Access,Remittances,Cost
9,FB.CBK.BRCH.P5,"Commercial bank branches (per 100,000 adults)",Financial Sector: Access,Financial Sector,Access,Commercial bank,Bank branches
10,FX.OWN.TOTL.PL.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
11,FB.CBK.DPTR.P3,"Depositors with commercial banks (per 1,000 ad...",Financial Sector: Access,Financial Sector,Access,Commercial bank,Depositors
12,FX.OWN.TOTL.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
13,FX.OWN.TOTL.FE.ZS,Account ownership at a financial institution o...,Financial Sector: Access,Financial Sector,Access,Ownership,Total
14,FB.CBK.BRWR.P3,"Borrowers from commercial banks (per 1,000 adu...",Financial Sector: Access,Financial Sector,Access,Commercial bank,Borrowers
15,FM.AST.DOMO.ZG.M3,Claims on other sectors of the domestic econom...,Financial Sector: Assets,Financial Sector,Assets,Asset,Other domestic sectors
16,FD.AST.PRVT.GD.ZS,Domestic credit to private sector by banks (% ...,Financial Sector: Assets,Financial Sector,Assets,Asset,Private
17,FS.AST.PRVT.GD.ZS,Domestic credit to private sector (% of GDP),Financial Sector: Assets,Financial Sector,Assets,Asset,Private
18,FM.AST.PRVT.ZG.M3,Claims on private sector (annual growth as % o...,Financial Sector: Assets,Financial Sector,Assets,Asset,Private
19,FD.RES.LIQU.AS.ZS,Bank liquid reserves to bank assets ratio (%),Financial Sector: Assets,Financial Sector,Assets,Reserves (or residential),Liquid
20,FS.AST.DOMO.GD.ZS,Claims on other sectors of the domestic econom...,Financial Sector: Assets,Financial Sector,Assets,Asset,Other domestic sectors
21,FM.AST.PRVT.GD.ZS,Monetary Sector credit to private sector (% GDP),Financial Sector: Assets,Financial Sector,Assets,Asset,Private
22,FM.AST.NFRG.CN,Net foreign assets (current LCU),Financial Sector: Assets,Financial Sector,Assets,Asset,Net foreign
23,FS.AST.DOMS.GD.ZS,Domestic credit provided by financial sector (...,Financial Sector: Assets,Financial Sector,Assets,Asset,Domestic
24,FS.AST.CGOV.GD.ZS,"Claims on central government, etc. (% GDP)",Financial Sector: Assets,Financial Sector,Assets,Asset,Central government
25,FM.AST.CGOV.ZG.M3,Claims on central government (annual growth as...,Financial Sector: Assets,Financial Sector,Assets,Asset,Central government
26,FB.BNK.CAPA.ZS,Bank capital to assets ratio (%),Financial Sector: Assets,Financial Sector,Assets,Bank,Capital to assets
27,FM.AST.DOMS.CN,Net domestic credit (current LCU),Financial Sector: Assets,Financial Sector,Assets,Asset,Domestic
28,FB.AST.NPER.ZS,Bank nonperforming loans to total gross loans (%),Financial Sector: Assets,Financial Sector,Assets,Asset,Nonperforming
29,CM.MKT.TRAD.GD.ZS,"Stocks traded, total value (% of GDP)",Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Traded
30,CM.MKT.LCAP.GD.ZS,Market capitalization of listed domestic compa...,Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Market capitalization of listed companies
31,CM.MKT.TRAD.CD,"Stocks traded, total value (current US$)",Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Traded
32,CM.MKT.LCAP.CD,Market capitalization of listed domestic compa...,Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Market capitalization of listed companies
33,CM.MKT.INDX.ZG,S&P Global Equity Indices (annual % change),Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Index
34,CM.MKT.LDOM.NO,"Listed domestic companies, total",Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Listed domestic companies
35,CM.MKT.TRNR,"Stocks traded, turnover ratio of domestic shar...",Financial Sector: Capital markets,Financial Sector,Capital markets,Markets (stock),Transport receipts (or Turnover ratio)
36,NY.GDP.DEFL.ZS,GDP deflator (base year varies by country),Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Gross domestic product,Deflator
37,NY.GDP.DEFL.KD.ZG.AD,"Inflation, GDP deflator: linked series (annual %)",Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Gross domestic product,Deflator
38,FP.CPI.TOTL.ZG,"Inflation, consumer prices (annual %)",Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Consumer price index,Total
39,FP.CPI.TOTL,Consumer price index (2010 = 100),Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Consumer price index,Total
40,PA.NUS.FCRF,"Official exchange rate (LCU per US$, period av...",Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Local currency to US dollar,IMF IFS code rf (official exchange rate)
41,NY.GDP.DEFL.KD.ZG,"Inflation, GDP deflator (annual %)",Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Gross domestic product,Deflator
42,FP.WPI.TOTL,Wholesale price index (2010 = 100),Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Wholesale price index,Total
43,PX.REX.REER,Real effective exchange rate index (2010 = 100),Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Real exchange rate,Real effective exchange rate
44,PA.NUS.ATLS,DEC alternative conversion factor (LCU per US$),Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Local currency to US dollar,Atlas method
45,NY.GDP.DEFL.ZS.AD,GDP deflator: linked series (base year varies ...,Financial Sector: Exchange rates & prices,Financial Sector,Exchange rates & prices,Gross domestic product,Deflator
46,FR.INR.LNDP,Interest rate spread (lending rate minus depos...,Financial Sector: Interest rates,Financial Sector,Interest rates,Interest rate,Lending rate minus deposit rate
47,FR.INR.RINR,Real interest rate (%),Financial Sector: Interest rates,Financial Sector,Interest rates,Interest rate,Real interest rate
48,FR.INR.RISK,Risk premium on lending (lending rate minus tr...,Financial Sector: Interest rates,Financial Sector,Interest rates,Interest rate,Risk premium
49,FR.INR.DPST,Deposit interest rate (%),Financial Sector: Interest rates,Financial Sector,Interest rates,Interest rate,Deposit
50,FR.INR.LEND,Lending interest rate (%),Financial Sector: Interest rates,Financial Sector,Interest rates,Interest rate,Lending
51,FM.LBL.BMNY.IR.ZS,Broad money to total reserves ratio,Financial Sector: Monetary holdings (liabilities),Financial Sector,Monetary holdings (liabilities),Liability,Broad money
52,FM.LBL.BMNY.GD.ZS,Broad money (% of GDP),Financial Sector: Monetary holdings (liabilities),Financial Sector,Monetary holdings (liabilities),Liability,Broad money
53,FM.LBL.BMNY.CN,Broad money (current LCU),Financial Sector: Monetary holdings (liabilities),Financial Sector,Monetary holdings (liabilities),Liability,Broad money
54,FM.LBL.BMNY.ZG,Broad money growth (annual %),Financial Sector: Monetary holdings (liabilities),Financial Sector,Monetary holdings (liabilities),Liability,Broad money

In [140]:
has_list = financial.apply(lambda row: isinstance(row['SubTopic2'], list) or isinstance(row['SubTopic3'], list), axis=1)


financial_with_lists = financial[has_list]
print(financial_with_lists)

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

# Gender

In [141]:
gender  = dfs["gender"]

In [146]:
with pd.option_context('display.max_colwidth', 200):

    display(gender)

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,SP.M18.2024.FE.ZS,Women who were first married by age 18 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 18,Age 20-24
1,SP.M15.2024.FE.ZS,Women who were first married by age 15 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 15,Age 20-24
2,SG.VAW.REAS.ZS,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Gender: Health,Gender,Health,Violence against women,Reason
3,SG.VAW.ARGU.ZS,Women who believe a husband is justified in beating his wife when she argues with him (%),Gender: Health,Gender,Health,Violence against women,Argue
4,SG.VAW.1549.ZS,Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of ever-partnered women ages 15-49),Gender: Health,Gender,Health,Violence against women,None
5,SG.VAW.BURN.ZS,Women who believe a husband is justified in beating his wife when she burns the food (%),Gender: Health,Gender,Health,Violence against women,Burns food
6,SG.VAW.GOES.ZS,Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Gender: Health,Gender,Health,Violence against women,Goes out
7,SG.VAW.NEGL.ZS,Women who believe a husband is justified in beating his wife when she neglects the children (%),Gender: Health,Gender,Health,Violence against women,Neglects children
8,SG.VAW.REFU.ZS,Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Gender: Health,Gender,Health,Violence against women,Refuse
9,SG.TIM.UWRK.MA,"Proportion of time spent on unpaid domestic and care work, male (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
10,SG.TIM.UWRK.FE,"Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
11,SG.DMK.SRCR.FN.ZS,"Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,None
12,SG.LAW.INDX,Women Business and the Law Index Score (scale 1-100),Gender: Public life & decision making,Gender,Public life & decision making,Law,Index
13,SG.GEN.PARL.ZS,Proportion of seats held by women in national parliaments (%),Gender: Public life & decision making,Gender,Public life & decision making,Gender,National parliaments
14,SG.DMK.ALLD.FN.ZS,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,Total development assistance and official aid

In [142]:
with pd.option_context('display.max_colwidth', 200):

    display(gender[gender['SubTopic2'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
1,SP.M15.2024.FE.ZS,Women who were first married by age 15 (% of women ages 20-24),Gender: Agency,Gender,Agency,None,Age 20-24

In [145]:
gender.loc[gender["Code"] == "SP.M15.2024.FE.ZS", "SubTopic2"] = "Married by age 15"

In [147]:
with pd.option_context('display.max_colwidth', 200):

    display(gender[gender['SubTopic3'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
4,SG.VAW.1549.ZS,Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of ever-partnered women ages 15-49),Gender: Health,Gender,Health,Violence against women,None
11,SG.DMK.SRCR.FN.ZS,"Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,None

In [148]:
gender.loc[gender["Code"] == "SG.VAW.1549.ZS", "SubTopic3"] = "Age 15-49"
gender.loc[gender["Code"] == "SG.DMK.SRCR.FN.ZS", "SubTopic3"] = "Age 15-49"

In [149]:
with pd.option_context('display.max_colwidth', 200):

    display(gender)

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,SP.M18.2024.FE.ZS,Women who were first married by age 18 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 18,Age 20-24
1,SP.M15.2024.FE.ZS,Women who were first married by age 15 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 15,Age 20-24
2,SG.VAW.REAS.ZS,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Gender: Health,Gender,Health,Violence against women,Reason
3,SG.VAW.ARGU.ZS,Women who believe a husband is justified in beating his wife when she argues with him (%),Gender: Health,Gender,Health,Violence against women,Argue
4,SG.VAW.1549.ZS,Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of ever-partnered women ages 15-49),Gender: Health,Gender,Health,Violence against women,Age 15-49
5,SG.VAW.BURN.ZS,Women who believe a husband is justified in beating his wife when she burns the food (%),Gender: Health,Gender,Health,Violence against women,Burns food
6,SG.VAW.GOES.ZS,Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Gender: Health,Gender,Health,Violence against women,Goes out
7,SG.VAW.NEGL.ZS,Women who believe a husband is justified in beating his wife when she neglects the children (%),Gender: Health,Gender,Health,Violence against women,Neglects children
8,SG.VAW.REFU.ZS,Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Gender: Health,Gender,Health,Violence against women,Refuse
9,SG.TIM.UWRK.MA,"Proportion of time spent on unpaid domestic and care work, male (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
10,SG.TIM.UWRK.FE,"Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
11,SG.DMK.SRCR.FN.ZS,"Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,Age 15-49
12,SG.LAW.INDX,Women Business and the Law Index Score (scale 1-100),Gender: Public life & decision making,Gender,Public life & decision making,Law,Index
13,SG.GEN.PARL.ZS,Proportion of seats held by women in national parliaments (%),Gender: Public life & decision making,Gender,Public life & decision making,Gender,National parliaments
14,SG.DMK.ALLD.FN.ZS,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,Total development assistance and official aid

In [150]:
has_list = gender.apply(lambda row: isinstance(row['SubTopic2'], list) or isinstance(row['SubTopic3'], list), axis=1)


gender_with_lists = gender[has_list]
print(gender_with_lists)

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

# Health

In [151]:
health  = dfs["health"]

In [174]:
with pd.option_context('display.max_colwidth', 200):

    display(health)

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,SH.MLR.NETS.ZS,Use of insecticide-treated bed nets (% of under-5 population),Health: Disease prevention,Health,Disease prevention,Malaria,Insecticide-treated bed nets
1,SH.STA.SMSS.RU.ZS,"People using safely managed sanitation services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
2,SH.IMM.MEAS,"Immunization, measles (% of children ages 12-23 months)",Health: Disease prevention,Health,Disease prevention,Immunization,Measles
3,SH.STA.SMSS.ZS,People using safely managed sanitation services (% of population),Health: Disease prevention,Health,Disease prevention,Stationary,NaN
4,SH.H2O.SMDW.RU.ZS,"People using safely managed drinking water services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Water,NaN
...,...,...,...,...,...,...,...
243,SH.UHC.TOTR.ZS,Proportion of population pushed or further pushed below the 60% median consumption poverty line by out-of-pocket health expenditure (%),Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed or further pushed below),60% median consumption poverty line
244,SH.UHC.OOPC.25.ZS,Proportion of population spending more than 25% of household consumption or income on out-of-pocket health care expenditure (%),Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (spending more),25% of household consumption or income
245,SH.UHC.FBPR.ZS,Proportion of population pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure (%),Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed further below),60% median consumption poverty line
246,SH.UHC.NOP1.ZS,Proportion of population pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%),Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed below),2.15(2017 PPP) poverty line
247,SH.UHC.OOPC.10.ZS,Proportion of population spending more than 10% of household consumption or income on out-of-pocket health care expenditure (%),Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (spending more),10% of household consumption or income

In [170]:
with pd.option_context('display.max_colwidth', 200):

    display(health[health['SubTopic2'].isna()])

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []

In [158]:
health.loc[health["Code"] == "SH.UHC.SRVS.CV.XD", ["SubTopic2", "SubTopic3"]] = ["Service Coverage", "Index"]

In [167]:
health.loc[health["Code"] == "SH.UHC.NOP2.ZS",  "SubTopic3"] = ["3.65(2017 PPP) poverty line"]
health.loc[health["Code"] == "SH.UHC.NOP1.ZS",  "SubTopic3"] = ["2.15(2017 PPP) poverty line"]
health.loc[health["Code"] == "SH.UHC.OOPC.10.ZS",  "SubTopic3"] = ["10% of household consumption or income"]
health.loc[health["Code"] == "SH.UHC.OOPC.25.ZS",  "SubTopic3"] = ["25% of household consumption or income"]

In [165]:
health.loc[health['Code'].str.startswith('SH.UHC') & 
           health['Code'].str.contains('NOP1|NOP2|NOPR', regex=True), "SubTopic2"] = "Poverty Line (pushed below)"

health.loc[health['Code'].str.startswith('SH.UHC') & 
           health['Code'].str.contains('FBP1|FBP2|FBPR', regex=True), "SubTopic2"] = "Poverty Line (pushed further below)"

health.loc[health['Code'].str.startswith('SH.UHC') & 
           health['Code'].str.contains('TOT1|TOT2|TOTR', regex=True), "SubTopic2"] = "Poverty Line (pushed or further pushed below)"

health.loc[health['Code'].str.startswith('SH.UHC') & 
           health['Code'].str.contains('OOPC', regex=True), "SubTopic2"] = "Poverty Line (spending more)"

In [163]:
health_subtopic3_mapping = {
    "NOPR": "60% median consumption poverty line",
    "FBP1": "2.15(2017 PPP) poverty line",
    "FBP2": "3.65(2017 PPP) poverty line",
    "TOT1": "2.15(2017 PPP) poverty line",
    "TOT2": "3.65(2017 PPP) poverty line",
    "TOTR": "60% median consumption poverty line",
    "FBPR": "60% median consumption poverty line"
}
health.loc[health["SubTopic3"].isna(), "SubTopic3"] = (
    health["Code"].str.split(".").str[2].map(health_subtopic3_mapping)
)

In [168]:
health[health['Code'].str.startswith('SH.UHC')]

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
236,SH.UHC.SRVS.CV.XD,UHC service coverage index,Health: Universal Health Coverage,Health,Universal Health Coverage,Service Coverage,Index
237,SH.UHC.NOP2.ZS,Proportion of population pushed below the $3.6...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed below),3.65(2017 PPP) poverty line
238,SH.UHC.NOPR.ZS,Proportion of population pushed below the 60% ...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed below),60% median consumption poverty line
239,SH.UHC.FBP1.ZS,Proportion of population pushed further below ...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed further below),2.15(2017 PPP) poverty line
240,SH.UHC.FBP2.ZS,Proportion of population pushed further below ...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed further below),3.65(2017 PPP) poverty line
241,SH.UHC.TOT1.ZS,Proportion of population pushed or further pus...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed or further pushed below),2.15(2017 PPP) poverty line
242,SH.UHC.TOT2.ZS,Proportion of population pushed or further pus...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed or further pushed below),3.65(2017 PPP) poverty line
243,SH.UHC.TOTR.ZS,Proportion of population pushed or further pus...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed or further pushed below),60% median consumption poverty line
244,SH.UHC.OOPC.25.ZS,Proportion of population spending more than 25...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (spending more),25% of household consumption or income
245,SH.UHC.FBPR.ZS,Proportion of population pushed further below ...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed further below),60% median consumption poverty line
246,SH.UHC.NOP1.ZS,Proportion of population pushed below the $2.1...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (pushed below),2.15(2017 PPP) poverty line
247,SH.UHC.OOPC.10.ZS,Proportion of population spending more than 10...,Health: Universal Health Coverage,Health,Universal Health Coverage,Poverty Line (spending more),10% of household consumption or income

In [169]:
with pd.option_context('display.max_colwidth', 200):

    display(health[health['SubTopic3'].isna()])

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
1,SH.STA.SMSS.RU.ZS,"People using safely managed sanitation services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
3,SH.STA.SMSS.ZS,People using safely managed sanitation services (% of population),Health: Disease prevention,Health,Disease prevention,Stationary,NaN
4,SH.H2O.SMDW.RU.ZS,"People using safely managed drinking water services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Water,NaN
5,SH.STA.BASS.UR.ZS,"People using at least basic sanitation services, urban (% of urban population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
6,SH.STA.BASS.RU.ZS,"People using at least basic sanitation services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
7,SH.STA.BASS.ZS,People using at least basic sanitation services (% of population),Health: Disease prevention,Health,Disease prevention,Stationary,NaN
13,SH.STA.HYGN.UR.ZS,"People with basic handwashing facilities including soap and water, urban (% of urban population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
14,SH.STA.HYGN.ZS,People with basic handwashing facilities including soap and water (% of population),Health: Disease prevention,Health,Disease prevention,Stationary,NaN
16,SH.STA.SMSS.UR.ZS,"People using safely managed sanitation services, urban (% of urban population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
18,SH.H2O.SMDW.ZS,People using safely managed drinking water services (% of population),Health: Disease prevention,Health,Disease prevention,Water,NaN
19,SH.H2O.BASW.RU.ZS,"People using at least basic drinking water services, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Water,NaN
20,SH.H2O.BASW.ZS,People using at least basic drinking water services (% of population),Health: Disease prevention,Health,Disease prevention,Water,NaN
21,SH.STA.HYGN.RU.ZS,"People with basic handwashing facilities including soap and water, rural (% of rural population)",Health: Disease prevention,Health,Disease prevention,Stationary,NaN
24,SH.H2O.BASW.UR.ZS,"People using at least basic drinking water services, urban (% of urban population)",Health: Disease prevention,Health,Disease prevention,Water,NaN
25,SH.H2O.SMDW.UR.ZS,"People using safely managed drinking water services, urban (% of urban population)",Health: Disease prevention,Health,Disease prevention,Water,NaN
27,SH.XPD.PVTD.CH.ZS,Domestic private health expenditure (% of current health expenditure),Health: Health systems,Health,Health systems,Expenditure,NaN
28,SH.XPD.GHED.GE.ZS,Domestic general government health expenditure (% of general government expenditure),Health: Health systems,Health,Health systems,Expenditure,NaN
29,SH.XPD.EHEX.CH.ZS,External health expenditure (% of current health expenditure),Health: Health systems,Health,Health systems,Expenditure,NaN
30,SH.XPD.GHED.GD.ZS,Domestic general government health expenditure (% of GDP),Health: Health systems,Health,Health systems,Expenditure,NaN
31,SH.XPD.GHED.CH.ZS,Domestic general government health expenditure (% of current health expenditure),Health: Health systems,Health,Health systems,Expenditure,NaN
34,SH.XPD.PVTD.PC.CD,Domestic private health expenditure per capita (current US$),Health: Health systems,Health,Health systems,Expenditure,NaN
35,SH.XPD.GHED.PC.CD,Domestic general government health expenditure per capita (current US$),Health: Health systems,Health,Health systems,Expenditure,NaN
37,SH.XPD.CHEX.GD.ZS,Current health expenditure (% of GDP),Health: Health systems,Health,Health systems,Expenditure,NaN
42,SH.XPD.PVTD.PP.CD,"Domestic private health expenditure per capita, PPP (current international $)",Health: Health systems,Health,Health systems,Expenditure,NaN
43,SH.XPD.CHEX.PC.CD,Current health expenditure per capita (current US$),Health: Health systems,Health,Health systems,Expenditure,NaN
44,SH.XPD.EHEX.PP.CD,"External health expenditure per capita, PPP (current international $)",Health: Health systems,Health,Health systems,Expenditure,NaN
46,SH.XPD.CHEX.PP.CD,"Current health expenditure per capita, PPP (current international $)",Health: Health systems,Health,Health systems,Expenditure,NaN
47,SH.XPD.EHEX.PC.CD,External health expenditure per capita (current US$),Health: Health systems,Health,Health systems,Expenditure,NaN
49,SH.XPD.GHED.PP.CD,"Domestic general government health expenditure per capita, PPP (current international $)",Health: Health systems,Health,Health systems,Expenditure,NaN
72,SH.STA.POIS.P5.MA,"Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)",Health: Mortality,Health,Mortality,Stationary,NaN
74,SH.STA.POIS.P5.FE,"Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)",Health: Mortality,Health,Mortality,Stationary,NaN
75,SH.STA.POIS.P5,"Mortality rate attributed to unintentional poisoning (per 100,000 population)",Health: Mortality,Health,Mortality,Stationary,NaN
76,SH.STA.AIRP.MA.P5,"Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)",Health: Mortality,Health,Mortality,Stationary,NaN
77,SH.STA.AIRP.FE.P5,"Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)",Health: Mortality,Health,Mortality,Stationary,NaN
78,SH.STA.AIRP.P5,"Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)",Health: Mortality,Health,Mortality,Stationary,NaN
82,SH.STA.WASH.P5,"Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)",Health: Mortality,Health,Mortality,Stationary,NaN
91,SN.ITK.SVFI.ZS,Prevalence of severe food insecurity in the population (%),Health: Nutrition,Health,Nutrition,Intake,NaN
95,SN.ITK.MSFI.ZS,Prevalence of moderate or severe food insecurity in the population (%),Health: Nutrition,Health,Nutrition,Intake,NaN

In [148]:
gender.loc[gender["Code"] == "SG.VAW.1549.ZS", "SubTopic3"] = "Age 15-49"
gender.loc[gender["Code"] == "SG.DMK.SRCR.FN.ZS", "SubTopic3"] = "Age 15-49"

In [149]:
with pd.option_context('display.max_colwidth', 200):

    display(gender)

,Code,Indicator Name,General Topic,Topic,SubTopic1,SubTopic2,SubTopic3
0,SP.M18.2024.FE.ZS,Women who were first married by age 18 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 18,Age 20-24
1,SP.M15.2024.FE.ZS,Women who were first married by age 15 (% of women ages 20-24),Gender: Agency,Gender,Agency,Married by age 15,Age 20-24
2,SG.VAW.REAS.ZS,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Gender: Health,Gender,Health,Violence against women,Reason
3,SG.VAW.ARGU.ZS,Women who believe a husband is justified in beating his wife when she argues with him (%),Gender: Health,Gender,Health,Violence against women,Argue
4,SG.VAW.1549.ZS,Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of ever-partnered women ages 15-49),Gender: Health,Gender,Health,Violence against women,Age 15-49
5,SG.VAW.BURN.ZS,Women who believe a husband is justified in beating his wife when she burns the food (%),Gender: Health,Gender,Health,Violence against women,Burns food
6,SG.VAW.GOES.ZS,Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Gender: Health,Gender,Health,Violence against women,Goes out
7,SG.VAW.NEGL.ZS,Women who believe a husband is justified in beating his wife when she neglects the children (%),Gender: Health,Gender,Health,Violence against women,Neglects children
8,SG.VAW.REFU.ZS,Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Gender: Health,Gender,Health,Violence against women,Refuse
9,SG.TIM.UWRK.MA,"Proportion of time spent on unpaid domestic and care work, male (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
10,SG.TIM.UWRK.FE,"Proportion of time spent on unpaid domestic and care work, female (% of 24 hour day)",Gender: Participation & access,Gender,Participation & access,Time,Unpaid work
11,SG.DMK.SRCR.FN.ZS,"Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,Age 15-49
12,SG.LAW.INDX,Women Business and the Law Index Score (scale 1-100),Gender: Public life & decision making,Gender,Public life & decision making,Law,Index
13,SG.GEN.PARL.ZS,Proportion of seats held by women in national parliaments (%),Gender: Public life & decision making,Gender,Public life & decision making,Gender,National parliaments
14,SG.DMK.ALLD.FN.ZS,"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",Gender: Public life & decision making,Gender,Public life & decision making,Decision making,Total development assistance and official aid

In [150]:
has_list = gender.apply(lambda row: isinstance(row['SubTopic2'], list) or isinstance(row['SubTopic3'], list), axis=1)


gender_with_lists = gender[has_list]
print(gender_with_lists)

Empty DataFrame
Columns: [Code, Indicator Name, General Topic, Topic, SubTopic1, SubTopic2, SubTopic3]
Index: []